export const ERROR_CODES = {
  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_SESSION_ID: 'INVALID_SESSION_ID',
  INVALID_USER_ID: 'INVALID_USER_ID',
  INVALID_VIDEO_URL: 'INVALID_VIDEO_URL',
  
  // Session errors
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_FULL: 'SESSION_FULL',
  SESSION_ENDED: 'SESSION_ENDED',
  USER_NOT_IN_SESSION: 'USER_NOT_IN_SESSION',
  
  // Video errors
  VIDEO_NOT_ACCESSIBLE: 'VIDEO_NOT_ACCESSIBLE',
  VIDEO_LOAD_FAILED: 'VIDEO_LOAD_FAILED',
  SYNC_FAILED: 'SYNC_FAILED',
  
  // Database errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  CACHE_ERROR: 'CACHE_ERROR',
  
  // Network errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  CONNECTION_LOST: 'CONNECTION_LOST',
  
  // General errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export const HTTP_STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const; 